### ISSUE TITLE
Data folder missing

### ISSUE THREAD

**Issue by Hofsmo** [iasonask/spatial-disaggregation#3]
Hi, this project looks very interesting and I would like to try it and maybe uses it for some analyses. However, it seems that the Data folder mentioned in the Readme is not available anymore. Is it possible to make it available or is it something that can be downloaded from somewhere?

Best regards
Sigurd

**Comment by iasonask** [comment]
Hi, thanks for reaching out. I'll try to make the data folders available again in the next few days.

**Comment by Hofsmo** [comment]
Many thanks :) .

**Comment by iasonask** [comment]
Please check now if it works and let me know.

**Comment by Hofsmo** [comment]
@iasonask It is working flawlessly now. Many thanks :)
