### ISSUE TITLE
"Data" folder access

### ISSUE THREAD

**Issue by jonasboee** [iasonask/spatial-disaggregation#7]
Hi!

It's stated that "For using the N490 class, you need to extract the [Data] folder in the project's directory".
However, the link does not appear to link to an open data repository.

Could you please advise on how to access the required data?

**Comment by iasonask** [comment]
Hi!

Please check again; it should be there now. Otherwise, let me know.

**Comment by jonasboee** [comment]
It worked now. Thank you!
